---
collections:
  - name: redhat.rhel_system_roles
    src: https://console.redhat.com/api/automation-hub/
  
  - name: redhatinsights.insights
    src: https://console.redhat.com/api/automation-hub/

  - name: community.vmware.vmware_tag_manager
    src: https://galaxy.ansible.com
    