---
- name: Setup a central metrics server with grafana and pcp
  hosts: "{{ vm_name }}"
  collections:
    - redhat.rhel_system_roles
  become: yes 

- name: Open Firewall for grafana
  hosts: "{{ vm_name }}"
  tasks:
    - firewalld:
        service: grafana
        permanent: yes
        immediate: yes
        state: enabled

- name: Use metrics systems role to configure grafana  
  hosts: "{{ vm_name }}"
  roles:
    - redhat.rhel_system_roles.metrics
  
    
  