---
- hosts: "{{ vm_name }}"
  become: yes
  vars:
    mssql_accept_microsoft_odbc_driver_17_for_sql_server_eula: true
    mssql_accept_microsoft_cli_utilities_for_sql_server_eula: true
    mssql_accept_microsoft_sql_server_standard_eula: true
    mssql_password: H3mlis_01 
    mssql_edition: Developer
    mssql_tcp_port: 1443
  roles:
    - microsoft.sql.server